### ISSUE TITLE
BaseSandbox.grep silently returns zero matches on every busybox image (GNU-only `-Z` + `2>/dev/null || true`) — regression from 0.5.5

### ISSUE THREAD

**Issue by bpshaver** [langchain-ai/deepagents#5177]
### Submission checklist

- [x] This is a bug, not a usage question.
- [x] I added a clear and descriptive title.
- [x] I searched existing issues and didn't find this.
- [x] I can reproduce this with the latest released version.
- [x] I included a minimal reproducible example and steps to reproduce.

### Area (Required)

- [x] deepagents (SDK)
- [ ] dcode
- [ ] talon
- [ ] acp
- [ ] evals
- [ ] harbor
- [ ] daytona
- [ ] modal
- [ ] quickjs
- [ ] runloop
- [ ] vercel
- [ ] langsmith-sandbox
- [ ] Other / not sure / general

### Related Issues / PRs

- #4628 — same flag, **different defect, and neither fix implies the other.** There, `-Z` is accepted and the NUL is destroyed *in transit* by a text-only transport, so the parser sees `path1:text` and returns a false **error** (`matches=None`). Here, `grep` **rejects `-Z` outright and never searches**, and the wrapper converts that into a false **empty success** (`matches=[]`, `error=None`). A fix for #4628 that makes the separator survive the transport does nothing for a `grep` that won't accept the flag; a capability check for this issue does nothing for a transport that eats NULs.
- #3470 — proposed the NUL separator that `-Z` now implements (auto-closed `not_planned`, but the approach landed).
- #5112 / #5111 — touch `_build_grep_cmd`, unrelated defect.

### Reproduction Steps / Example Code (Python)

```python
# A. The mechanism. No sandbox, no container, no Docker.
#
# Shows the command `_build_grep_cmd` emits cannot distinguish "grep rejected my
# options and never searched" from "grep searched and found nothing".

import subprocess

from deepagents.backends.protocol import ExecuteResponse
from deepagents.backends.sandbox import _build_grep_cmd, _parse_grep_output

cmd = _build_grep_cmd("apple", "/tmp/p", None, None)
print(cmd)
# grep -rHnFZ  -e apple /tmp/p 2>/dev/null || true

# A `grep` that rejects -Z without searching, which is exactly what busybox does
# with an unknown option: message on stderr, exit 2, no search performed.
busybox = "grep() { echo 'grep: unrecognized option: Z' >&2; return 2; }; "
r = subprocess.run(["sh", "-c", busybox + cmd], capture_output=True, text=True)
print(repr(r.stdout), r.returncode)
# '' 0        <-- `2>/dev/null` ate the message, `|| true` ate the exit code

failed = _parse_grep_output(
    ExecuteResponse(output=r.stdout, exit_code=r.returncode, truncated=False), "/tmp/p"
)
genuine = _parse_grep_output(
    ExecuteResponse(output="", exit_code=0, truncated=False), "/tmp/p"
)
print(failed)             # GrepResult(error=None, matches=[], truncated=False)
print(genuine)            # GrepResult(error=None, matches=[], truncated=False)
print(failed == genuine)  # True  <-- total failure is indistinguishable from no-match

```

```python
# B. End-to-end on a real container. Needs a reachable Docker daemon.
#
# The smallest possible BaseSandbox: `execute` shells into a container via the
# docker CLI. `upload_files`/`download_files` are abstract so they must exist,
# but `grep` never calls them, so the fixture goes in through `execute`.

import subprocess

from deepagents.backends.protocol import ExecuteResponse
from deepagents.backends.sandbox import BaseSandbox


class CliSandbox(BaseSandbox):
    def __init__(self, container: str) -> None:
        self._container = container

    @property
    def id(self) -> str:
        return self._container

    def execute(self, command: str, *, timeout: int | None = None) -> ExecuteResponse:
        p = subprocess.run(
            ["docker", "exec", self._container, "sh", "-c", command],
            capture_output=True,
            text=True,
        )
        return ExecuteResponse(
            output=p.stdout + p.stderr, exit_code=p.returncode, truncated=False
        )

    def upload_files(self, files):
        raise NotImplementedError

    def download_files(self, paths):
        raise NotImplementedError


def run(image: str) -> None:
    container = subprocess.run(
        ["docker", "run", "-d", "--rm", image, "sleep", "300"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    try:
        s = CliSandbox(container)
        s.execute("mkdir -p /tmp/p && printf 'first line\napple 42\n' > /tmp/p/data.txt")

        # Control, using a flag every grep supports: the file exists and the
        # pattern really does match. Rules out a bad fixture.
        print(image)
        print("  grep -c apple           ->", s.execute("grep -c apple /tmp/p/data.txt").output.strip())
        print("  grep -rHnFZ exit code   ->", s.execute("grep -rHnFZ -e apple /tmp/p").exit_code)
        print("  BaseSandbox.grep        ->", s.grep("apple", path="/tmp/p"))
    finally:
        subprocess.run(["docker", "kill", container], capture_output=True)


for image in ("python:3.13-slim", "python:3.12-alpine"):
    run(image)
```

### Error Message and Stack Trace (if applicable)

There is no error message, and that is the substance of the report. Output of B:

```
python:3.13-slim
  grep -c apple           -> 1
  grep -rHnFZ exit code   -> 0
  BaseSandbox.grep        -> GrepResult(error=None, matches=[{'path': '/tmp/p/data.txt', 'line': 2, 'text': 'apple 42'}], truncated=False)

python:3.12-alpine
  grep -c apple           -> 1          <-- the match IS there
  grep -rHnFZ exit code   -> 2          <-- grep: unrecognized option: Z
  BaseSandbox.grep        -> GrepResult(error=None, matches=[], truncated=False)
```

### Description

`BaseSandbox.grep` returns zero matches, with `error=None`, for every possible
pattern on any sandbox image whose `grep` is busybox rather than GNU — Alpine
being the common case. Nothing is logged and nothing raises. An agent doing
`grep` to orient itself in a codebase is told, credibly, that the code it is
looking for does not exist.

**Cause.** Two individually reasonable decisions meet in `_build_grep_cmd`:

```python
grep_opts = "-rHnFZ"
base = f"grep {grep_opts} {glob_pattern} -e {pattern_escaped} {search_path} 2>/dev/null"
return f"{base} || true"
```

`-Z` is a GNU extension. Busybox grep does not implement it and rejects the whole
invocation with exit 2 without searching. `2>/dev/null` then discards the
diagnostic and `|| true` rewrites the exit code to 0, so `_parse_grep_output`
receives empty output with a success status and correctly concludes "no matches".
Every layer behaves as written; the composition loses the failure.

**This is a regression in 0.7.** 0.5.5 used `grep_opts = "-rHnF"`, which busybox
accepts, and the *identical* script above on the *identical* Alpine image returns
the match under 0.5.5 and returns nothing under 0.7.0:

| `BaseSandbox.grep("apple")` on `python:3.12-alpine` | Result |
| --- | --- |
| deepagents 0.5.5 (`-rHnF`) | `matches=[{'path': '/tmp/p/data.txt', 'line': 2, 'text': 'apple 42'}]` |
| deepagents 0.7.0 (`-rHnFZ`) | `matches=[]`, `error=None` |

I appreciate that the comment in `_build_grep_cmd` already documents the
`2>/dev/null` + `|| true` masking as a known pre-existing limitation, and that a
portable fix (`set -o pipefail` is not POSIX) was deliberately deferred. The
reason I am filing anyway is that `-Z` changed the blast radius: the masking used
to hide edge cases like an unreadable search root, and now it hides the total,
permanent failure of `grep` on a mainstream base image.

**Expected.** Either `grep` works on busybox images as it did in 0.5.5, or the
failure is visible — a populated `GrepResult.error`, or a raised exception, or at
minimum a warning. Any of those is recoverable. Silence is not.

**Possible directions**, in case they are useful — happy to send a PR if you want
one, though I will wait to be assigned per the template:

1. Probe the capability once per backend and fall back to the existing
   `_GREP_PATH_GLOB_TEMPLATE` route when `-Z` is unavailable. That template
   already emits the same `path\0line:text` records and, per its own docstring,
   deliberately omits `|| true` so real failures surface. The mechanism is
   already in the file; only the routing is missing. Would also give #4628 a
   NUL-free path to fall back to.
2. Drop `-Z` in favour of `-H` plus a parser that splits on the last `:` before a
   line number, accepting the colon-in-filename ambiguity that #3470 raised.
3. Keep `-Z` but stop discarding failure: capture stderr and treat a non-zero
   exit that produced no output as an error rather than an empty result.

(1) looks cheapest and fixes the silence rather than just this instance of it.

### Environment / System Info

```
OS: macOS 26.3 (arm64)
Python: 3.13.3
deepagents: 0.7.0
langchain: 1.3.14
langchain-core: 1.5.2

Docker Engine: 29.3.1
Failing image: python:3.12-alpine (BusyBox v1.37.0)
Working image: python:3.13-slim (GNU grep)
```

Also reproduced on Python 3.12.10, and with the k8s equivalent of the sandbox
above, so it is neither interpreter- nor Docker-specific — it tracks only which
`grep` is on PATH.
