### ISSUE TITLE
`RunnableWithFallbacks` no longer accepted as `model`

### ISSUE THREAD

**Issue by davidallada** [langchain-ai/deepagents#2154]
## Checked other resources

- [x] This is a bug, not a usage question.
- [x] I added a clear and descriptive title.
- [x] I searched existing issues and didn't find this.
- [x] I can reproduce this with the latest released version.
- [x] I included a minimal reproducible example and steps to reproduce.

## Area

- [x] deepagents (SDK)

## Related Issues / PRs

None found.

## Reproduction Steps / Example Code (Python)

```python
from langchain.chat_models import init_chat_model
from deepagents import create_deep_agent

primary = init_chat_model("anthropic:claude-sonnet-4-5-20250929")
fallback = init_chat_model("anthropic:claude-haiku-4-5-20251001")
model_with_fallback = primary.with_fallbacks([fallback])

# Raises AttributeError: 'RunnableWithFallbacks' object has no attribute 'startswith'
agent = create_deep_agent(model=model_with_fallback, tools=[])
```

## Error Message and Stack Trace

```
File ".../deepagents/graph.py", line 184, in create_deep_agent
    model = get_default_model() if model is None else resolve_model(model)
File ".../deepagents/_models.py", line 27, in resolve_model
    if model.startswith("openai:"):
AttributeError: 'RunnableWithFallbacks' object has no attribute 'startswith'
```

## Description

`create_deep_agent` no longer accepts a `RunnableWithFallbacks` (returned by LangChain's `.with_fallbacks()`) as the `model` parameter. This worked in 0.4.1 but broke in 0.4.12 when `resolve_model` was extracted into `_models.py`.

**Root cause:** In 0.4.1, `graph.py` handled the model parameter inline with an `elif isinstance(model, str)` branch — any non-string value (including `RunnableWithFallbacks`) was passed through as-is via duck typing. In 0.4.12, this was refactored into `resolve_model`, which introduced an explicit `isinstance(model, BaseChatModel)` check. `RunnableWithFallbacks` is not a subclass of `BaseChatModel`, so it falls through to `model.startswith("openai:")` and raises `AttributeError`.

**Proposed fix:** Extend the `isinstance` check in `resolve_model` to also accept `RunnableWithFallbacks`, restoring the 0.4.1 duck-typing behavior:

```python
from langchain_core.runnables.fallbacks import RunnableWithFallbacks

def resolve_model(model: str | BaseChatModel) -> BaseChatModel:
    if isinstance(model, (BaseChatModel, RunnableWithFallbacks)):
        return model  # type: ignore[return-value]
    if model.startswith("openai:"):
        return init_chat_model(model, use_responses_api=True)
    return init_chat_model(model)
```

`RunnableWithFallbacks` wraps a `BaseChatModel` and supports the full invocation interface (`.invoke()`, `.ainvoke()`, `.stream()`, etc.), so deepagents can use it anywhere a `BaseChatModel` is expected.

**Workaround:** Pass the primary model directly and use `ModelFallbackMiddleware` instead:

```python
from langchain.chat_models import init_chat_model
from langchain.agents.middleware import ModelFallbackMiddleware
from deepagents import create_deep_agent

model = init_chat_model("anthropic:claude-sonnet-4-5-20250929")

agent = create_deep_agent(
    model=model,
    tools=[],
    middleware=[ModelFallbackMiddleware("anthropic:claude-haiku-4-5-20251001")],
)
```

## Environment / System Info

```
OS: Linux
Python: 3.12
deepagents: 0.4.12 (regression from 0.4.1)
langchain-core: 0.3.x
```

**Comment by eyurtsev** [comment]
`create_agent` hasn't been accepting RunnableBinding since the 1.0 release of langchain. i.e., this worked because of duck typing, but wasn't expected to be working (i.e., RunnableBinding isn't supported)

We've generally recommended using middleware with langchain 1.0.

@davidallada would these middleware work for your use case?

https://docs.langchain.com/oss/python/langchain/middleware/built-in#model-fallback
https://docs.langchain.com/oss/python/langchain/middleware/built-in#model-retry

**Comment by davidallada** [comment]
@eyurtsev Thanks for the quick response! 
The Middleware approach does work, but is less convenient for me and my dev team.

We will use the Middleware approach, thank you!
